# Generated by Django 2.1.5 on 2019-02-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tweet',
            unique_together={('tweet_id', 'tweet_text', 'published_date')},
        ),
    ]
