# Generated by Django 2.1.5 on 2019-02-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20190213_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tweet',
            unique_together=set(),
        ),
    ]
