# Generated by Django 2.1.5 on 2019-02-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20190213_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
