# Generated by Django 2.1.5 on 2019-02-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20190213_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='tweet',
            unique_together={('tweet_id', 'tweet_text', 'published_date')},
        ),
    ]
